### ISSUE TITLE
Make openseeface-gd First Time User Experience better

### ISSUE THREAD

**Issue by fire** [you-win/openseeface-gd#18]
- [ ] Use one archive
- [ ] Provide builds on Windows, Linux and Mac
- [ ] Does not also require installing openseeface separately
- [ ] Use https://github.com/chriskiehl/Gooey.git to make a gui for the python program https://github.com/emilianavt/OpenSeeFace

**Comment by you-win** [comment]
>  Use one archive

There are bundled face tracker and non-bundled face tracker builds for convenience and file size considerations

> Provide builds on Windows, Linux and Mac

This should be handled once #15 (ci builds) is implemented. Providing manual builds is not a high priority since changes are pretty frequent

> Does not also require installing openseeface separately

Covered above, bundled application contains the the face tracker

> Use https://github.com/chriskiehl/Gooey.git to make a gui for the python program https://github.com/emilianavt/OpenSeeFace

Not necessary. On windows this is handled automatically via the 'Start facetracker' button. #7 covers running the corresponding python command on mac/linux. It's not difficult to implement but I primarily use Windows 10 as my dev environment

Overall, I do agree the first time user experience is lacking due to a few lingering bugs
- [ ] Face tracking offsets are not set correctly when the model is first loaded. This causes the model to basically fold in half until offsets are set by the user
- [ ] Random crashes with no logs when the application regains focus, probably due to cpu usage? (Windows 10)
- [ ] Settings are only applied when the 'Apply properties' button is pressed, which is somewhat unexpected

**Comment by you-win** [comment]
Probably closed by #34
